name: "Test and build"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: "Test and build"
    runs-on: "ubuntu-22.04"
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: 'golangci-lint'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: 'run tests'
        run: go test -v ./...
